apiVersion: v1
kind: Service
metadata:
  name: book-catalog
  namespace: book-catalog
spec:
  selector:
    app: book-catalog
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer