apiVersion: v1
kind: ConfigMap
metadata:
  name: book-catalog-config
  namespace: book-catalog
data:
  application.properties: |
    # JPA Configuration
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true

    # Server configuration
    server.port=8080

    # Actuator Configuration
    management.endpoints.web.exposure.include=health,info
    management.endpoint.health.show-details=always