
services:
  book-catalog-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bookdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER=org.postgresql.Driver
    depends_on:
      - postgres
    networks:
      - backend
      - frontend
    volumes:
      - app-data:/app/data
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    expose:
      - "5432" # Only exposed within the network, not to the host
    environment:
      - POSTGRES_DB=bookdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  postgres-data:
  app-data: